[build-system]
requires = ["hatchling>=1.25.0"]
build-backend = "hatchling.build"

[project]
name = "shared"
version = "0.1.0"
description = "Example utility package for the monorepo"
readme = "README.md"
authors = [{ name = "Your Name" }]
requires-python = ">=3.9"
license = { text = "MIT" }

[tool.hatch.build.targets.wheel]
force-include = { "src/shared.py" = "shared.py" }
